news_sites:
  lanacion:
    url: https://www.lanacion.com.ar
    queries:
      homepage_article_links: '.com-title a'
      article_body: '.com-paragraph'
      article_title: '.--threexl'
  clarin:
    url: https://www.clarin.com
    queries:
      homepage_article_links: '.link_article'
      article_body: '.body-nota p'
      article_title: '#title'